### ISSUE TITLE
This is an obnoxious name for this project on Pypi.

### ISSUE THREAD

**Issue by proafxin** [Inndy/pyent#1]
Is there a reason why you picked pyent even though your repo has nothing to do with Elementary Number Theory? 
ENT is widely accepted as a short form for Elementary Number Theory in mathematics. But you saw it fit to use this name for your random sequence tester even though the short form of your repository is not even close to `pyent`: https://pypi.org/project/pyent/

Please consider renaming your pypi package and removing the previous releases so that the name is freed. I am currently developing a library for elementary number theory but cannot use `pyent` or `pynt` because both are reserved. I believe the library I am writing could help a lot of people, specially, in academia. More so because there are no real reusable libraries in python for number theory that covers a reasonable amount of topics. Sympy has some useful functions but it's far from an ideal library for extension or good coverage of topics.

**Comment by Inndy** [comment]
[`ent`](https://www.fourmilab.ch/random/) is a program to evaluate entropy of binary stream which created two decades ago and this project provides a fast library to do the same test by using Cython.

Yeah, maybe ENT is widely accepted in your field, but your field is relatively small to others. Asking to unpublish a package from public package registry will break existing project depend on it. Stop being rude, selfish and stupid.

**Comment by proafxin** [comment]
A primer on how to announce how stupid and ignorant someone is. Your project is specific for some random sequence testing, it doesn't matter how old it is. And no, I don't think anybody worth their salt would care about your stupid remarks.

"Yeah, maybe ENT is widely accepted in your field, but your field is relatively small to others" thanks for clarifying what a clown you are.
